- debug:
    msg: "{{item.state}} {{item.machines|last}}"
  with_items: '{{vms}}'
  

- name: Upgrade host
  # TODO: change to ovirt_hosts, when Ansible 2.6 is out:
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    name: "{{ async_item.name }}"
    state: "{{ state }}"
  async: 900
  poll: 0
  with_items: "{{ vms }}"
  loop_control:
    loop_var: "async_item"
  register: async_results

- name: Check sync status
  async_status: "jid={{ async_result_item.ansible_job_id }}"
  with_items: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30